### ISSUE TITLE
Can you please also add ASP MVC views

### ISSUE THREAD

**Issue by fasteddys** [adams85/aspnetskeleton2#2]
Hello I am trying to use this skeleton for asp core view for a dashboard, can you also add ASP MVC views

**Comment by adams85** [comment]
Hi!

As a matter of fact, the dashboard used to use MVC views earlier but I migrated it to Razor Pages because I found that architecture a better fit for this kind of an application. So I don't plan to re-add this, however, if you still want this, you can create a branch at [the last commit](https://github.com/adams85/aspnetskeleton2/commit/79da68b612d9f838ae1408db0627a779d6d08f2f) before the migration and cherry-pick the changes made after that.
