### ISSUE TITLE
Is this active and do you accept pull requests?

### ISSUE THREAD

**Issue by xecrets** [adams85/aspnetskeleton2#5]
Hi!

Very useful this... thanks!

Are you accepting pull requests to this repository - specifically for POTools?

Regards,

Svante

**Comment by xecrets** [comment]
Hi, thanks for quick response! I totally get the "temporary inactive" status... My primary interest right now is to do some minor improvements to the resx extractor, specifically add support for translator comments and a publishing profile to enable creation of  a single file executable for easier use outside of the web template context. I am planning to use it for localization of an Avalonia UI-based app. I might also want to fix what I think is a bug in the underlying Karambolo.PO library, as it's currently blowing up for me with a 'An item with the same key has already been added' argument exception in merge mode ;-) .

I'd be happy to upgrade the POTools to .NET 8 as well I guess. The ASP.NET solution is a little out of scope for me, but POTools stands on it's own as far as I can tell.

**Comment by adams85** [comment]
> My primary interest right now is to do some minor improvements to the resx extractor, specifically add support for translator comments

Sounds awesome!

> and a publishing profile to enable creation of a single file executable for easier use outside of the web template context.

Regarding publishing, please be aware that I have no plans to distribute the tool in a binary form. There has been a discussion about this: https://github.com/adams85/aspnetskeleton2/issues/1#issuecomment-729890030

Currently, the recommended way to include POTools is to copy its source code into your project and to modify it according to the needs of your application.

So please send only those changes upstream that are not specific to your application (general improvements, bug fixes, etc.)

> I might also want to fix what I think is a bug in the underlying Karambolo.PO library, as it's currently blowing up for me with a 'An item with the same key has already been added' argument exception in merge mode ;-)

If it turns out to be an actual bug, I'd really appreciate if you opened an issue or PR about it.

I'd be surprised though if it were a bug in Karambolo.PO. That library is pretty battle-tested now. If there's an issue, then it's more likely in POTools.

Anyway, here are some hints where you can start investigation:
* https://github.com/adams85/po/issues/24#issuecomment-1751361072
* https://github.com/adams85/po/blob/1.11.1/source/Karambolo.PO/POKey.cs

**Comment by xecrets** [comment]
> > and a publishing profile to enable creation of a single file executable for easier use outside of the web template context.
> 
> Regarding publishing, please be aware that I have no plans to distribute the tool in a binary form. There has been a discussion about this: [#1 (comment)](https://github.com/adams85/aspnetskeleton2/issues/1#issuecomment-729890030)
It's just a publishing profile, making it easier to handle locally. It's not intended for general binary tool distribution.

> So please send only those changes upstream that are not specific to your application (general improvements, bug fixes, etc.)
Of course.

> > I might also want to fix what I think is a bug in the underlying Karambolo.PO library, as it's currently blowing up for me with a 'An item with the same key has already been added' argument exception in merge mode ;-)
> 
> If it turns out to be an actual bug, I'd really appreciate if you opened an issue or PR about it.
It wasn't. It was a bug in the resx extractor, not properly handling embedded newlines in the value.
The fix will also be included.

Would you like me to do the .NET 8 upgrade as well? (Just the POTools...)

You can sneak a peek here: https://github.com/adams85/aspnetskeleton2/compare/master...xecrets:aspnetskeleton2:feature/resxandpublish .

**Comment by adams85** [comment]
> It's just a publishing profile, making it easier to handle locally. It's not intended for general binary tool distribution.

Ah, ok, I see.

> It wasn't. It was a bug in the resx extractor, not properly handling embedded newlines in the value.
The fix will also be included.

Great news, thanks!

> Would you like me to do the .NET 8 upgrade as well? (Just the POTools...)

Hmm, I think it wouldn't make much sense to upgrade the target framework to .NET 8 now, for the following reasons:

* The whole project is on .NET 6 currently.
* .NET 6 is still supported.
* POTools doesn't need post-.NET 6 features.

However, probably we should add `<RollForward>Major</RollForward>` to the csproj, so it can be run on .NET 8 without having the .NET 6 runtime installed.

**Comment by adams85** [comment]
Closing as resolved by #6
